= Clojure Check: A command-line interface to checkers via nREPL

== Rationale

This is a quicker alternative to `lein eastwood` or `lein kibit` when you already have an nREPL running. The main driver is to be able to refer this from Vim for tools like https://github.com/w0rp/ale[ALE]

== Usage

=== Building

I use https://github.com/Masterminds/glide[glide] to build this project.

NOTE: I had to run `git config --global http.https://gopkg.in.followRedirects true` with the latest git.

[source,shell]
----
$ glide install
$ go build <1>
----
<1> Creates ./clojure-check

=== CLI usage

You can get output from eastwood & kibit on a running nREPL via

[source,shell]
----
$ ./output localhost:33999 app.website < src/app/website.clj
----

=== REPL setup

[source,clojure]
.~/.lein/profiles.clj
----
{:user
 {:dependencies
  [[jonase/eastwood "0.2.3" :exclusions [org.clojure/clojure]]
   [jonase/kibit "0.1.3" :exclusions [org.clojure/clojure]]]}}
----

[source,clojure]
.~/.boot/profile.boot
----
;; OR merge this with your cider task
(deftask linters "Linter profile"
  []
  (require 'boot.repl)
  (swap! @(resolve 'boot.repl/*default-dependencies*)
         concat '[[jonase/eastwood "0.2.3" :exclusions [org.clojure/clojure]]
                  [jonase/kibit "0.1.3" :exclusions [org.clojure/clojure]])
  identity)
----

== Editor integration

Inspired by http://ddg.gg/[fzf] I have included a plugin folder in this repo which allows easy integration with Vim. I welcome similar PRs for other editors.

==== Vim - ALE

There is ALE integration available in this repo. It depends on Fireplace to find connection details.

----
Plug 'w0rp/ale'
Plug 'SevereOverfl0w/clojure-check', {'do': './install'}
----
